#!/usr/bin/bash

#----------------------------------------------------------------
# This script is not for execute directly.
# Please use 'source ./setup'.
#----------------------------------------------------------------

echo "Get NITROSDK_ROOT: $NITROSDK_ROOT"

export TWLSDK_ROOT=`cygpath -m $PWD`
echo "Set TWLSDK_ROOT: $TWLSDK_ROOT"
